version: '3.7'
services:
  minio1:
    image: minio/minio:latest
    hostname: minio1
    volumes:
      - /data:/data1
    environment:
      MINIO_ROOT_USER: kubitre
      MINIO_ROOT_PASSWORD: MyLastSecuritySmokeMazero1998
    expose: 9000
    command: server http://minio/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - "traefik.http.routers.whoami.rule=Host(`mins3.kubitre.space`)"
      - traefik.http.services.my-container-service.loadbalancer.server.port=9000
  
  Vault:
    image: vault
    volumes:
      - /vault:/vault/data
    cap_add:
      - IPC_LOCK
    expose:
      - 8200
    entrypoint: vault server
    labels:
      - traefik.http.routers.whoami.rule=Host(`vault.kubitre.space`)
      - traefik.http.services.my-container-service.loadbalancer.server.port=8200

  reverse-proxy:
    image: traefik:v2.3
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443 
      - --providers.docker=true
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./data/traefik.config.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`traf.kubitre.space`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik-traefik.loadbalancer.server.port=888"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=kubitre:$1$MPdJER/m$h5gB16/IkH01m1nxMAUx10"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"