version: '3.7'
services:
  minio1:
    image: minio/minio:latest
    hostname: minio1
    volumes:
      - /data:/data1
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: kubitre
      MINIO_ROOT_PASSWORD: MyLastSecuritySmokeMazero1998
    command: server http://minio/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  Vault:
    image: vault
    ports:
      - "8200:8200"
    volumes:
      - /vault:/vault/data
    cap_add:
      - IPC_LOCK
    entrypoint: vault server