global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

log:
  level: DEBUG
  format: json

api:
  insecure: true
  dashboard: true

